# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: falsk-app-svc
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
  - name: flask-app-svc
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32000
---
